config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end
  namespace :admin do
    resources :stories
  end
  namespace :admin do
    resources :orders
  end
  namespace :admin do
    resources :menus
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
  get 'sign_out', :to => 'devise/sessions#destroy', :as => :des_user_session
end

  root 'menus#index'
  resources :users do
    resources :orders
  end

  post 'allpay/result'
  post 'allpay/return'

  resources :menus do
    resources :orders do
      post :confirm, :on => :collection
      get :checkout
    end
    resources :likes
  end

  resource :cart

  scope :path => '/api/v1/', :module => "api_v1", :defaults => { :format => :json }, :as => 'v1' do
    post "login" => "auth#login"
    post "logout" => "auth#logout"

    resources :menus
    resources :orders
  end

  resources :people

end

app/models/admin/story.rb
class Admin::Story < Story
end

app/models/story.rb
class Story < ActiveRecord::Base

    has_attached_file :pic, :styles => { :large => "600x600>", :medium => "300x300>", :small => "250x250>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :pic, :content_type => /\Aimage\/.*\Z/

end

app/controllers/admin/stories_controller.rb
class Admin::StoriesController < AdminController
  before_action :set_admin_story, only: [:show, :edit, :update, :destroy]

  # GET /admin/stories
  # GET /admin/stories.json
  def index
    @admin_stories = Admin::Story.all
  end

  # GET /admin/stories/1
  # GET /admin/stories/1.json
  def show
  end

  # GET /admin/stories/new
  def new
    @admin_story = Admin::Story.new
  end

  # GET /admin/stories/1/edit
  def edit
  end

  # POST /admin/stories
  # POST /admin/stories.json
  def create
    @admin_story = Admin::Story.new(admin_story_params)

    respond_to do |format|
      if @admin_story.save
        format.html { redirect_to @admin_story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @admin_story }
      else
        format.html { render :new }
        format.json { render json: @admin_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/stories/1
  # PATCH/PUT /admin/stories/1.json
  def update
    respond_to do |format|
      if @admin_story.update(admin_story_params)
        format.html { redirect_to @admin_story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_story }
      else
        format.html { render :edit }
        format.json { render json: @admin_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/stories/1
  # DELETE /admin/stories/1.json
  def destroy
    @admin_story.destroy
    respond_to do |format|
      format.html { redirect_to admin_stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_story
      @admin_story = Admin::Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_story_params
      params.require(:admin_story).permit(:momheader, :momcontents, :momcontents_1, :momcontents_2, :momcontents_3)
    end
end

app/helpers/admin/stories_helper.rb
module Admin::StoriesHelper
end

app/views/admin/stories/_form.html.erb
<%= form_for(@admin_story) do |f| %>
  <% if @admin_story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_story.errors.count, "error") %> prohibited this admin_story from being saved:</h2>

      <ul>
      <% @admin_story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :momheader %><br>
    <%= f.text_field :momheader %>
  </div>
  <div class="field">
    <%= f.label :momcontents %><br>
    <%= f.text_area :momcontents %>
  </div>
  <div class="field">
    <%= f.label :momcontents_1 %><br>
    <%= f.text_area :momcontents_1 %>
  </div>
  <div class="field">
    <%= f.label :momcontents_2 %><br>
    <%= f.text_area :momcontents_2 %>
  </div>
  <div class="field">
    <%= f.label :momcontents_3 %><br>
    <%= f.text_area :momcontents_3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/stories/edit.html.erb
<h1>Editing Admin Story</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_story %> |
<%= link_to 'Back', admin_stories_path %>

app/views/admin/stories/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="container">
<h1>後台媽媽故事管理頁面</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>媽媽title</th>
      <th>媽媽故事</th>
      <th>媽媽故事第一段</th>
      <th>媽媽故事第二段</th>
      <th>媽媽故事第三段</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_stories.each do |admin_story| %>
      <tr>
        <td><%= admin_story.momheader %></td>
        <td><%= admin_story.momcontents %></td>
        <td><%= admin_story.momcontents_1 %></td>
        <td><%= admin_story.momcontents_2 %></td>
        <td><%= admin_story.momcontents_3 %></td>
        <td><%= link_to 'Show', admin_story,:class=>"btn btn-primary" %>
            <%= link_to 'Edit', edit_admin_story_path(admin_story),:class=>"btn btn-primary"  %>
            <%= link_to 'Destroy', admin_story, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新媽媽故事', new_admin_story_path, :class => "btn btn-success" %>
<%= link_to '訂單管理', admin_orders_path, :class => "btn btn-primary" %>
<%= link_to '菜單管理', admin_menus_path, :class => "btn btn-primary" %>
<%= link_to '回到前台', root_path, :class => "btn btn-default" %>

app/views/admin/stories/new.html.erb
<h1>New Admin Story</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_stories_path %>

app/views/admin/stories/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<p>
  <strong>Momheader:</strong>
  <%= @admin_story.momheader %>
</p>

<p>
  <strong>Momcontents:</strong>
  <%= @admin_story.momcontents %>
</p>

<p>
  <strong>Momcontents 1:</strong>
  <%= @admin_story.momcontents_1 %>
</p>

<p>
  <strong>Momcontents 2:</strong>
  <%= @admin_story.momcontents_2 %>
</p>

<p>
  <strong>Momcontents 3:</strong>
  <%= @admin_story.momcontents_3 %>
</p>

<%= link_to 'Edit', edit_admin_story_path(@admin_story) %> |
<%= link_to 'Back', admin_stories_path %>