config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end
  namespace :admin do
    resources :stories
  end
  namespace :admin do
    resources :orders
  end
  namespace :admin do
    resources :menus
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
  get 'sign_out', :to => 'devise/sessions#destroy', :as => :des_user_session
end

  root 'menus#index'
  resources :users do
    resources :orders
  end

  post 'allpay/result'
  post 'allpay/return'

  resources :menus do
    resources :orders do
      post :confirm, :on => :collection
      get :checkout
    end
    resources :likes
  end

  resource :cart

  scope :path => '/api/v1/', :module => "api_v1", :defaults => { :format => :json }, :as => 'v1' do
    post "login" => "auth#login"
    post "logout" => "auth#logout"

    resources :menus
    resources :orders
  end

  resources :people

end

app/models/admin/order.rb
class Admin::Order < Order
end

app/models/order.rb
class Order < ActiveRecord::Base

  attr_accessor :address_area, :address_road

  belongs_to :user
  belongs_to :menu
  has_many :trades, :dependent => :destroy
  validates_presence_of :order_name, :order_address, :menu_id, :menu_count
  validates_numericality_of :menu_count, :only_integer => true
  validates_numericality_of :order_phone, :only_integer => true
  validates_length_of :order_phone, :is => 10

  before_save :setup_total
  before_create :setup_total
  after_create :consume_stock
  after_create :fill_user_data

  def paid?
    trades.exists?(paid: true)
  end

  def total
    self.menu_count.to_i * self.menu.price
  end

  protected
  # 總價直接存在後台
  def setup_total
    self.total_price = self.total
  end

  def consume_stock
    stock = self.menu.in_stock_qty
    stock = stock - self.menu_count
    self.menu.update(:in_stock_qty => stock )
  end

  def fill_user_data
    u = self.user
    if u
      u.name = self.order_name
      u.phone = self.order_phone
      u.address = self.order_address
      u.save!
    end
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
# class Admin::OrdersController < ApplicationController
  before_action :set_admin_order, only: [:show, :edit, :update, :destroy]

  def orders_all
    @admin_orders = Admin::Menu::Order.find(params[:menu_id])
  end


  # GET /admin/orders
  # GET /admin/orders.json
  def index
    @admin_orders = Admin::Order.all.page(params[:page]).per(7)
    @admin_menus = Admin::Menu.all.page(params[:page]).per(5)
  end

  # GET /admin/orders/1
  # GET /admin/orders/1.json
  def show
  end

  # GET /admin/orders/new
  def new
    @admin_order = Admin::Order.new
  end

  # GET /admin/orders/1/edit
  def edit
  end

  # POST /admin/orders
  # POST /admin/orders.json
  def create
    @admin_order = Admin::Order.new(admin_order_params)

    respond_to do |format|
      if @admin_order.save
        format.html { redirect_to @admin_order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @admin_order }
      else
        format.html { render :new }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/orders/1
  # PATCH/PUT /admin/orders/1.json
  def update
    respond_to do |format|
      if @admin_order.update(admin_order_params)
        format.html { redirect_to @admin_order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_order }
      else
        format.html { render :edit }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/orders/1
  # DELETE /admin/orders/1.json
  def destroy
    @admin_order.destroy
    respond_to do |format|
      format.html { redirect_to admin_orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_order
      @admin_order = Admin::Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_order_params
      params.require(:admin_order).permit(:total_price, :menu_count, :order_name, :order_phone, :order_address, :order_email,:menu_id,:id)
    end
end

app/controllers/api_v1/orders_controller.rb
class ApiV1::OrdersController < ApiController

  def create
    @order = Order.new( menu_id: params[:menu_id],
                        menu_count: params[:menu_count],
                        order_name: params[:name],
                        order_phone: params[:phone],
                        order_address: params[:address],
                        order_email: params[:email],
                        from_phone: params[:from_phone] )
    @order.user = current_user

    if @order.save
      render :json => { :message => "OK", :order_id => @order.id }
    else
      render :json => { :errors => @order.errors.full_messages }, :status => 400
    end
  end

  def index
    @orders = Menu.last.orders.order(:id => :desc).page(params[:page]).per(5)
  end


end

app/controllers/orders_controller.rb
require 'allpay'
class OrdersController < ApplicationController

  def confirm
    @menu = Menu.find(params[:menu_id])

    # combine select menu and text_field
    full_order_address = params[:order][:order_address] || params[:order][:address_area] + params[:order][:address_road]
    @order = @menu.orders.new(order_params)
    # re-assign order_address with new combined address
    @order.order_address = full_order_address
      respond_to do |format|
       format.html {render :template => "menus/wrong"}
       format.js {
         render :template => "orders/confirm"
       }
      end
  end

  def create
    @menu = Menu.find(params[:menu_id])
    @order = @menu.orders.new(order_params)

    @order.user = current_user

    if @menu.enough?(@order.menu_count)
      if @order.save
       redirect_to menu_path(@menu)
      else
       render :template => "menus/wrong"
      end
    else
     render :template => "menus/out_of_stock"
    end
  end

  def checkout

    order = Order.find(params[:order_id])
    order.update(:payment_method => "Credit")
    if order.paid?
      redirect_to user_orders_path(current_user), notice: '已經付過款'
    else
      trade = order.trades.create!
      allpay = Allpay.new
      @checkout_params = {
        MerchantID: allpay.merchant_id,
        MerchantTradeNo: trade.trade_number,
        MerchantTradeDate: Time.now.strftime('%Y/%m/%d %H:%M:%S'),
        PaymentType: :aio,
        TotalAmount: order.total_price,
        TradeDesc: :'My Order',
        ItemName: :"便當",
        ChoosePayment: order.payment_method,
        ReturnURL: 'http://requestb.in/131oj771',
        OrderResultURL: allpay_result_url
      }
      @checkout_params[:CheckMacValue] = allpay.make_mac(@checkout_params)
    end
  end


  def index
    @orders = current_user.orders.page(params[:page]).per(5)
  end

  private

  def order_params
    params.require(:order).permit(:order_name,:order_phone,:order_address,:menu_count,:payment_method,:status,:total_price,:menu_id,:user_id,:order_email,:from_phone,:road,:area)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_form.html.erb
<%= form_for(@admin_order) do |f| %>
  <% if @admin_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_order.errors.count, "error") %> prohibited this admin_order from being saved:</h2>

      <ul>
      <% @admin_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <table class="table-hover table">
   <tr class="field">
     <td><%= f.label :menu_id, "便當編號" %></td>
     <td><%= f.text_field :menu_id,:class=>"form-control form-width" %></td>
   </tr>
   <tr class="field">
     <td><%= f.label :menu_count, "便當個數" %></td>
     <td><%= f.text_field :menu_count,:class=>"form-control form-width" %></td>
   </tr>
   <tr class="field">
     <td><%= f.label :order_name, "訂購者姓名" %></td>
     <td><%= f.text_field :order_name,:class=>"form-control form-width" %></td>
   </tr>
   <tr class="field">
     <td><%= f.label :order_phone, "訂購者電話" %></td>
     <td><%= f.text_field :order_phone,:class=>"form-control form-width" %></td>
   </tr>
   <tr class="field">
     <td><%= f.label :order_address, "訂購者地址" %></td>
     <td><%= f.text_area :order_address,:class=>"form-control" %></td>
   </tr>
   <tr class="field">
     <td><%= f.label :order_email, "訂購者email" %></td>
     <td><%= f.text_field :order_email,:class=>"form-control form-width" %></td>
   </tr>
   <tr class="actions">
     <td><%= f.submit "更新訂單",:class=>"btn btn-default" %></td>
     <td></td>
   </tr>
 </table>








<% end %>

app/views/admin/orders/edit.html.erb
<div class="container">
  <div class="row">
    <h1>修改訂單</h1>

    <%= render 'form' %>
    <hr>
    <%= link_to 'Show', @admin_order,:class=>"btn btn-primary"  %>
    <%= link_to 'Back', admin_orders_path,:class=>"btn btn-primary"  %>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class="container">
<h1>後台訂單管理頁面</h1>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>便當編號</th>
        <th>訂單總價</th>
        <th>訂單便當個數</th>
        <th>訂購者</th>
        <th>訂購者電話</th>
        <th>訂購者地址</th>
        <th>訂購時間</th>
        <th>訂單狀態</th>
        <!-- <th>訂購者email</th> -->
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @admin_orders.order(:created_at => :desc).each do |admin_order| %>
        <tr>
          <td><%= admin_order.menu_id %></td>
          <td><%= admin_order.total_price %></td>
          <td><%= admin_order.menu_count %></td>
          <td><%= admin_order.order_name %></td>
          <td><%= admin_order.order_phone %></td>
          <td>
          <%= admin_order.order_address[0..10] %><br>
          <%= admin_order.order_address[11..-1] %>
          </td>
          <td>
          <%= admin_order.created_at.localtime.strftime("%Y/%m/%d") %><br><%= admin_order.created_at.localtime.strftime("%_I:%M %P") %>
          </td>
          <td><%= admin_order.paid? ? :已付款 : :未付款 %></td>
          <!-- <td><%#= admin_order.order_email %></td> -->
          <td><%= link_to 'Show', admin_order,:class => "btn btn-primary" %>
              <%= link_to 'Edit', edit_admin_order_path(admin_order),:class => "btn btn-primary" %>
              <%= link_to 'Destroy', admin_order, method: :delete, data: { confirm: 'Are you sure?' },:class => "btn btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @admin_orders %>

  <br>
  <%= link_to '新增訂單', new_admin_order_path, :class => "btn btn-success" %>
  <%= link_to '菜單管理', admin_menus_path, :class => "btn btn-primary" %>
  <%= link_to '會員管理', admin_users_path, :class => "btn btn-primary" %>
  <%= link_to '媽媽故事管理', admin_stories_path, :class => "btn btn-primary" %>
  <%= link_to '回到前台', root_path, :class => "btn btn-default" %>
  </div>

app/views/admin/orders/new.html.erb
<div class="container">
  <div class="row">
  <h1>新訂單</h1>

    <%= render 'form' %>

   <table class="table">
    <th><%= link_to 'Back', admin_orders_path,:class=>"btn btn-primary" %></th>
   </table>
  </div>
</div>

app/views/admin/orders/orders_all.html.erb
<% @admin_orders.each do |order| %>
<ul>
<li><%= order.menu_id %></li>
</ul>
<% end %>

app/views/admin/orders/show.html.erb
<div class="container">
 <div class="row">
  <table class="table table-striped">
    <hr>
      <tr>
        <th>
          <strong>Total price:</strong>
        </th>
        <td><%= @admin_order.total_price %></td>
      </tr>

      <tr>
        <th>
          <strong>Menu count:</strong>
        </th>
        <td><%= @admin_order.menu_count %></td>
      </tr>

      <tr>
        <th>
          <strong>Order name:</strong>
        </th>
        <td><%= @admin_order.order_name %></td>
      </tr>

      <tr>
        <th>
          <strong>Order phone:</strong>
        </th>
        <td><%= @admin_order.order_phone %></td>
      </tr>

      <tr>
        <th>
          <strong>Order address:</strong>
        </th>
        <td><%= @admin_order.order_address %></td>
      </tr>

      <tr>
        <th>
          <strong>Order email:</strong>
        </th>
        <td><%= @admin_order.order_email %></td>
      </tr>

      <tr>
        <th><%= link_to 'Edit', edit_admin_order_path(@admin_order),:class=>"btn btn-primary" %>
          <%= link_to 'Back', admin_orders_path,:class=>"btn btn-primary" %>
        </th>
        <td></td>
      </tr>
  </table>
 </div>
</div>