config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end
  namespace :admin do
    resources :stories
  end
  namespace :admin do
    resources :orders
  end
  namespace :admin do
    resources :menus
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
  get 'sign_out', :to => 'devise/sessions#destroy', :as => :des_user_session
end

  root 'menus#index'
  resources :users do
    resources :orders
  end

  post 'allpay/result'
  post 'allpay/return'

  resources :menus do
    resources :orders do
      post :confirm, :on => :collection
      get :checkout
    end
    resources :likes
  end

  resource :cart

  scope :path => '/api/v1/', :module => "api_v1", :defaults => { :format => :json }, :as => 'v1' do
    post "login" => "auth#login"
    post "logout" => "auth#logout"

    resources :menus
    resources :orders
  end

  resources :people

end

app/models/admin/user.rb
class Admin::User < User
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  devise :omniauthable, :omniauth_providers => [:facebook]

  # create many to many (menus) relation
  has_many :user_menus
  has_many :menus, :through => :user_menus, :source => "menu"

  # create many to many (likes) relation
  has_many :likes
  has_many :menu_likes, :through => :likes, :source => "menu"

  # create one to many (orders) relation
  has_many :orders, -> { order("id DESC") }

  validates_presence_of :friendly_id
  validates_uniqueness_of :friendly_id

  before_validation :setup_friendly_id
  before_save :ensure_authentication_token

  def to_param
    self.friendly_id
  end

  def self.from_omniauth(auth)
    user = where( fb_uid: auth.uid ).first

    unless user
      user = self.new
      user.fb_uid = auth.uid
      user.email = auth.info.email
      user.fb_image = auth.info.image
      user.password = Devise.friendly_token[0,20]
    end

    if auth.credentials
      user.fb_access_token = auth.credentials.token
      user.fb_expires_at = Time.at(auth.credentials.expires_at)
    end

    user.save
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

 def self.get_facebook_user_data(access_token)
    conn = Faraday.new(:url => 'https://graph.facebook.com/me')
    response = conn.get "/me", { :access_token => access_token }
    data = JSON.parse(response.body)

    if response.status == 200
      data
    else
      Rails.logger.warn(data)
      nil
    end
  end

  def generate_authentication_token
    token = nil

    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end

    self.authentication_token = token
  end

  def setup_friendly_id
    self.friendly_id ||= SecureRandom.hex(8)
  end


  protected

  def ensure_authentication_token
    if authentication_token.blank?
      self.authentication_token = generate_authentication_token
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]

  # GET /admin/users
  # GET /admin/users.json
  def index
    @admin_users = Admin::User.all.page(params[:page]).per(5)
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @admin_user = Admin::User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @admin_user = Admin::User.new(admin_user_params)

    respond_to do |format|
      if @admin_user.save
        format.html { redirect_to @admin_user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @admin_user }
      else
        format.html { render :new }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1
  # PATCH/PUT /admin/users/1.json
  def update
    respond_to do |format|
      if @admin_user.update(admin_user_params)
        format.html { redirect_to @admin_user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_user }
      else
        format.html { render :edit }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @admin_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = Admin::User.find_by_friendly_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_user_params
      params.require(:admin_user).permit(:name, :phone, :address, :email, :friendly_id)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in(@user)
      # , :event => :authentication #this will throw if @user is not activated
      redirect_to root_path(:facebookbuy => "true")

    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, :only => [:edit, :update]

  def edit
  end

  def show
  end

  def update
    # @user.update(user_params)
    if @user.update(user_params)
      flash[:notice] = "成功儲值"
      redirect_to user_orders_path(current_user)
    else
      flash[:alert] = "儲值失敗"
      render :action => :edit
    end
  end

  private

  def set_user
    @user = User.find_by_friendly_id(params[:id])
  end

  def user_params
    params.require(:user).permit(:storage_money)
  end




end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for(@admin_user) do |f| %>
  <% if @admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
      <% @admin_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table class="table table-hover">

    <tr class="field">
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name,:class=>"form-control form-width" %></td>
    </tr>
    <tr class="field">
      <td><%= f.label :phone %></td>
      <td><%= f.text_field :phone,:class=>"form-control form-width" %></td>
    </tr>
    <tr class="field">
      <td><%= f.label :address %></td>
      <td><%= f.text_field :address,:class=>"form-control form-width" %></td>
    </tr>
    <tr class="field">
      <td><%= f.label :email %></td>
      <td><%= f.text_field :email,:class=>"form-control form-width" %></td>
    </tr>
    <tr class="actions">
      <td><%= f.submit "更新使用者",:class=>"btn btn-default" %></td>
      <td></td>
    </tr>
</table>
<% end %>

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <h1>修改會員</h1>

    <%= render 'form' %>
    <hr>
    <%= link_to 'Show', @admin_user,:class=>"btn btn-primary"  %>
    <%= link_to 'Back', admin_users_path,:class=>"btn btn-primary"  %>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
  <h1>會員管理</h1>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th>會員編號</th>
          <th>姓名</th>
          <th>電話</th>
          <th>地址</th>
          <th>Email</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @admin_users.each do |admin_user| %>
          <tr>
          <td><%= admin_user.id %></td>
            <td><%= admin_user.name %></td>
            <td><%= admin_user.phone %></td>
            <td>
                <%= admin_user.address[0..10] %><br>
                <%= admin_user.address[11..-1] %>
            </td>
            <td><%= admin_user.email %></td>
            <td><%= link_to 'Show', admin_user,:class => "btn btn-primary" %>
                <%= link_to 'Edit', edit_admin_user_path(admin_user),:class => "btn btn-primary" %>
                <%= link_to 'Destroy', admin_user, method: :delete, data: { confirm: 'Are you sure?' },:class => "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= paginate @admin_users %><br>

    <%= link_to '新會員', new_admin_user_path, :class => "btn btn-success" %>
    <%= link_to '訂單管理', admin_orders_path, :class => "btn btn-primary" %>
    <%= link_to '菜單管理', admin_menus_path, :class => "btn btn-primary" %>
    <%= link_to '媽媽故事管理', admin_stories_path, :class => "btn btn-primary" %>
    <%= link_to '回到前台', root_path, :class => "btn btn-default" %>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="container">
  <div class="row">
   <h1>新會員</h1>

    <%= render 'form' %>

    <table class="table">
    <th><%= link_to 'Back', admin_users_path,:class=>"btn btn-primary" %></th>
    </table>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
 <div class="row">
  <table class="table table-striped">
    <hr>
      <tr>
        <th>
          <strong>姓名:</strong>
        </th>
        <td><%= @admin_user.name %></td>
      </tr>

      <tr>
        <th>
          <strong>電話:</strong>
        </th>
        <td><%= @admin_user.phone %></td>
      </tr>

      <tr>
        <th>
          <strong>地址:</strong>
        </th>
        <td><%= @admin_user.address %></td>
      </tr>

      <tr>
        <th>
          <strong>Email:</strong>
        </th>
        <td><%= @admin_user.email %></td>
      </tr>

      <tr>
        <th>
          <%= link_to 'Edit', edit_admin_user_path(@admin_user),:class =>"btn btn-primary" %>
          <%= link_to 'Back', admin_users_path,:class =>"btn btn-primary" %>
        </th>
        <td></td>
      </tr>
  </table>
 </div>
</div>