config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end
  namespace :admin do
    resources :stories
  end
  namespace :admin do
    resources :orders
  end
  namespace :admin do
    resources :menus
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
  get 'sign_out', :to => 'devise/sessions#destroy', :as => :des_user_session
end

  root 'menus#index'
  resources :users do
    resources :orders
  end

  post 'allpay/result'
  post 'allpay/return'

  resources :menus do
    resources :orders do
      post :confirm, :on => :collection
      get :checkout
    end
    resources :likes
  end

  resource :cart

  scope :path => '/api/v1/', :module => "api_v1", :defaults => { :format => :json }, :as => 'v1' do
    post "login" => "auth#login"
    post "logout" => "auth#logout"

    resources :menus
    resources :orders
  end

  resources :people

end

app/models/admin/menu.rb
class Admin::Menu < Menu
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  # create many to many (uers) relation
  has_many :user_menus, :dependent => :destroy #when delete menu will also delete related datbase menu_id in  users_menu !?
  has_many :users, :through => :user_menus, :source => "user"

  # create many to many (likes) relation
  has_many :likes
  has_many :user_likes, :through => :likes, :source => "user", :dependent => :destroy

  # create one to many (orders) relation
  has_many :orders, :dependent => :destroy


  has_attached_file :mompic, :styles => { :large => "600x600>", :medium => "300x300>", :small => "250x250>", :thumb => "100x100>",:special => "70x70>" }, :default_url => "/images/:style/missing.png",
  :path => ":rails_root/public/system/menus/:attachment/:id_partition/:style/:filename"
  validates_attachment_content_type :mompic, :content_type => /\Aimage\/.*\Z/
  validates_numericality_of :in_stock_qty, :only_integer => true
  validates_numericality_of :price, :only_integer => true, :greater_than => 1

  def find_like_by_user(user)
    self.likes.where(:user_id => user.id).first
  end

  def enough?(qty)
    self.in_stock_qty - qty >= 0
  end

  def menu_date
    self.created_at.strftime("%_m /%_d")
  end

  def chef_name
    mominfo.at(0..6)
  end

  def chef_experience
    mominfo.at(7..20)
  end

  def menu_cuisine_1
    contents.at(0..3)
  end

  def menu_cuisine_2
    contents.at(4..7)
  end

  def menu_cuisine_3
    contents.at(8..11)
  end

  def menu_cuisine_4
    contents.at(12..14)
  end

  def menu_cuisine_5
    contents.at(15..17).blank?? "":contents.at(15..17)
  end

  def menu_cuisine_6
    contents.at(18..19).blank?? "":contents.at(18..19)
  end

end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < AdminController
# class Admin::MenusController < ApplicationController
  before_action :set_admin_menu, only: [:show, :edit, :update, :destroy]

  # GET /admin/menus
  # GET /admin/menus.json
  def index
    @admin_menus = Admin::Menu.all.page(params[:page]).per(5)
  end

  # GET /admin/menus/1
  # GET /admin/menus/1.json
  def show
    @menu = Menu.find(params[:id])
  end

  # GET /admin/menus/new
  def new
    @admin_menu = Admin::Menu.new
  end

  # GET /admin/menus/1/edit
  def edit
  end

  # POST /admin/menus
  # POST /admin/menus.json
  def create
    @admin_menu = Admin::Menu.new(admin_menu_params)

    respond_to do |format|
      if @admin_menu.save
        format.html { redirect_to @admin_menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @admin_menu }
      else
        format.html { render :new }
        format.json { render json: @admin_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/menus/1
  # PATCH/PUT /admin/menus/1.json
  def update
    respond_to do |format|
      if @admin_menu.update(admin_menu_params)
        format.html { redirect_to @admin_menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_menu }
      else
        format.html { render :edit }
        format.json { render json: @admin_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/menus/1
  # DELETE /admin/menus/1.json
  def destroy
    @admin_menu.destroy
    respond_to do |format|
      format.html { redirect_to admin_menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_menu
      @admin_menu = Admin::Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_menu_params
      params.require(:admin_menu).permit(:title, :contents, :price, :likes_count, :in_stock_qty, :mominfo, :mompic)
    end
end

app/controllers/api_v1/menus_controller.rb
class ApiV1::MenusController < ApiController

  def show
    @menu = Menu.last
  end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  def index
    @menu = Menu.last
    @order = Order.new
    @story = Story.last

    if current_user
      @order.order_name = current_user.name
      @order.order_phone = current_user.phone
      @order.order_address = current_user.address
    end

  end

end

app/helpers/admin/menus_helper.rb
module Admin::MenusHelper
end

app/helpers/menus_helper.rb
module MenusHelper

  def split_menu_content(string)
     cuisine_1 = string.at(0..3)
     cuisine_2 = string.at(4..7)
     cuisine_3 = string.at(8..11)
     cuisine_4 = string.at(12..14)
     cuisine_5 = string.at(15..17).blank?? "empty":string.at(15..17)
     cuisine_6 = string.at(18..-1).blank?? "empty":string.at(18..-1)

     return [cuisine_1,cuisine_2,cuisine_3,cuisine_4,cuisine_5,cuisine_6]
  end
end

app/views/admin/menus/_form.html.erb
   <%= form_for(@admin_menu) do |f| %>
      <% if @admin_menu.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@admin_menu.errors.count, "error") %> prohibited this admin_menu from being saved:</h2>

          <ul>
          <% @admin_menu.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <table class="table table-hover">
        <tr class="field">
          <td><%= f.label :contents, "便當內容" %></td>
          <td><%= f.text_area :contents,:class=>"form-control form-width" %></td>
        </tr>
        <tr class="field">
          <td><%= f.label :price, "便當價格" %></td>
          <td><%= f.text_field :price,:class=>"form-control form-width" %></td>
        </tr>
        <tr class="field">
          <td><%= f.label :likes_count, "按讚數" %></td>
          <td><%= f.text_field :likes_count,:class=>"form-control form-width" %></td>
        </tr>
        <tr class="field">
          <td><%= f.label :in_stock_qty, "便當庫存" %></td>
          <td><%= f.text_field :in_stock_qty,:class=>"form-control form-width" %></td>
        </tr>
        <tr class="field">
          <td><%= f.label :mominfo, "媽媽資訊" %></td>
          <td><%= f.text_field :mominfo,:class=>"form-control form-width" %></td>
        </tr>
        <tr class="field">
          <td><%= f.label :mompic, "上傳媽媽照片" %></td>
          <td><%= f.file_field :mompic %></td>
        </tr>
        <tr class="actions">
          <td><%= f.submit "更新菜單",:class=>"btn btn-default" %></td>
          <td></td>
        </tr>
      </table>
    <% end %>

app/views/admin/menus/edit.html.erb
<div class="container">
  <div class="row">
    <h1>修改菜單</h1>
    <%= render 'form' %>
    <hr>
      <%= link_to 'Show', @admin_menu,:class=>"btn btn-primary" %>
      <%= link_to 'Back', admin_menus_path,:class=>"btn btn-primary" %>
  </div>
</div>

app/views/admin/menus/index.html.erb
<div class="container">
<h1>後台菜單管理頁面</h1>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>便當編號</th>
        <th>便當內容</th>
        <th>便當價格</th>
        <th>喜歡的人數</th>
        <th>便當庫存</th>
        <th>媽媽資訊</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @admin_menus.each do |admin_menu| %>
        <tr>
          <td><%= admin_menu.id %></td>
          <td>
          <%= admin_menu.contents[0..10] %><br>
          <%= admin_menu.contents[11..-1] %>
          </td>
          <td><%= admin_menu.price %></td>
          <td><%= admin_menu.likes_count %></td>
          <td><%= admin_menu.in_stock_qty %></td>
          <td><%= admin_menu.mominfo %></td>
          <!-- <td><%#= image_tag(admin_menu.mompic(:small)) %></td> -->
          <td><%= link_to 'Show', admin_menu,:class => "btn btn-primary"  %>
              <%= link_to 'Edit', edit_admin_menu_path(admin_menu),:class => "btn btn-primary"  %>
              <%= link_to 'Destroy', admin_menu, method: :delete, data: { confirm: 'Are you sure?' },:class => "btn btn-danger"  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= paginate @admin_menus %>

  <%= link_to '新增便當', new_admin_menu_path, :class => "btn btn-success" %>
  <%= link_to '訂單管理', admin_orders_path, :class => "btn btn-primary" %>
  <%= link_to '會員管理', admin_users_path, :class => "btn btn-primary" %>
  <%= link_to '媽媽故事管理', admin_stories_path, :class => "btn btn-primary" %>
  <%= link_to '回到前台', root_path, :class => "btn btn-default" %>
  </div>

app/views/admin/menus/new.html.erb
<div class="container">
  <div class="row">
   <h1>New Admin Menu</h1>

    <%= render 'form' %>

    <table class="table">
    <th><%= link_to 'Back', admin_menus_path,:class=>"btn btn-primary" %></th>
    </table>
  </div>
</div>

app/views/admin/menus/show.html.erb
<div class="container">
 <div class="row"><!-- <p id="notice"><%= notice %></p> -->
  <table class="table table-striped">
    <hr>
      <tr>
        <th>
          <strong>Title:</strong>
        </th>
        <td><%= @admin_menu.title %></td>
      </tr>

      <tr>
        <th>
          <strong>Contents:</strong>
        </th>
        <td><%= @admin_menu.contents %></td>
      </tr>

      <tr>
        <th>
          <strong>Price:</strong>
        </th>
        <td><%= @admin_menu.price %></td>
      </tr>

      <tr>
        <th>
          <strong>Likes count:</strong>
        </th>
        <td><%= @admin_menu.likes_count %></td>
      </tr>

      <tr>
        <th>
          <strong>In stock qty:</strong>
        </th>
        <td><%= @admin_menu.in_stock_qty %></td>
      </tr>

      <tr>
        <th>
          <strong>Mominfo:</strong>
        </th>
        <td><%= @admin_menu.mominfo %></td>
      </tr>

      <tr>
        <th>
          <strong>Mompic:</strong>
        </th>
        <td><%= image_tag(@menu.mompic(:medium)) %></td>
      </tr>

      <tr>
        <th><%= link_to 'Edit', edit_admin_menu_path(@admin_menu),:class=>"btn btn-primary" %>
          <%= link_to 'Back', admin_menus_path,:class=>"btn btn-primary" %></th>
      </tr>
  </table>
 </div>
</div>